### ISSUE TITLE
Portfolio in Tabular Format

### ISSUE THREAD

**Issue by debugger24** [TechUniv2018/cryptocoin-folio#54]
As a registered user I should be able to see my portfolio in a tabular format so that I could make necessary changes in them and increase profitability.

**Acceptance Criteria:**

| **Scenario** | **User is in homepage**                                                   |
|----------|-----------------------------------------------------------------------|
| GIVEN    | User is logged in                                                    |
| WHEN     | User choose on "My Portfolio" option                                  |
| THEN     | View Portfolio Page gets loaded where user can see his/her Portfolio. |

| **Scenario** | **User is in view Portfolio Page**         |
|----------|----------------------------------------|
| GIVEN    | Registered user is logged in           |
| WHEN     | User choose Edit Portfolio option      |
| THEN     | User redirected to edit portfolio page #52  |

| **Scenario** | **User is in view Portfolio Page**         |
|----------|----------------------------------------|
| GIVEN    | Registered user is logged in           |
| WHEN     | User selects any column in tabular portfolio      |
| THEN     | Sort the portfolio as per that column  |

![Wireframe View Portfolio](https://raw.githubusercontent.com/shubhamzanwar/cryptocoin-folio/master/Docs/wireframes/viewportfolio2.png)

**Tasks:**

- [x] List of all the coins with purchased should be shown in tabular format.
- [x] Each row should have coin symbol, coin name, price, quantity and net value, Current price and profilt and loss associated with the transaction.
- [x] If there is profit in a particular coin its row should be green and if it is loss, its row should be red.
